### ISSUE TITLE
create-dmg fails on Apple Silicon Macs

### ISSUE THREAD

**Issue by philc** [Bearer/gon#12]
Running on an Apple Silicon Mac fails with this message:

    ...
    Done fixing permissions.
    Blessing started
    bless: The 'openfolder' is not supported on Apple Silicon devices.

This can be fixed by removing the -openfolder argument to `bless` in `create-dmg`.

You must then run `go generate ./...` to regenerate the embedded create-dmg script.

This is the same issue as https://github.com/mitchellh/gon/issues/64. See more context [in this commit](https://github.com/skeema/gon/commit/bb695520e216d19d9941ae33f5e7e66ab0d660a6) of another gon fork.

Note that gon is using a vendored version of [create-dmg](https://github.com/create-dmg/create-dmg) from 2019, which has since deprecated the "-bless" flag.

[Related issue](https://github.com/LinusU/node-appdmg/issues/204) on a NodeJS tool for creating dmg files.

**Comment by cfabianski** [comment]
It should be resolved now :)
